### PR TITLE
Upgrade to CakePHP 3

### PR DESCRIPTION
**Pull request by dakota**
This PR upgrades BoostCake to CakePHP 3. It makes full use of CakePHP3 templates and supports horizontal forms (Inline forms have not been implemented yet).

As part of this PR, support for Bootstrap 2.x has been removed.

### CODE REVIEW

**Comment by angelxmoreno** [comment]
maybe this PR would be best on a new branch? thoughts @slywalker ?

**Comment by dakota** [comment]
I agree that it should be on it's own branch, but it doesn't look like GitHub has the ability to submit a PR for a new branch (Unless I missed it).

**Comment by angelxmoreno** [comment]
@dakota you did not miss it. @slywalker has to create it first

**Comment by eyoung100** [comment]
Please Implement this PR, as this plugin looks like the best implementation of Bootstrap in CakePHP....  I'll use it...

**Comment by dakota** [comment]
@eyoung100, the best implementation by far is now https://github.com/FriendsOfCake/bootstrap-ui

**Pull request closed without merging**
