### PR TITLE
Set label text without having to create array 'text' key.

### PR DESCRIPTION
**Pull request by wvdongen**
When creating horizontal forms the input default settings specify the label class. Therefore the 'quick setting' of the label text isn't possible anymore (array merge will fail), for example:

``` php
 echo $this->Form->input('birth_dt', array(
    'label' => 'Date of birth',
 ));
```

So we needed to do the following:

``` php
 echo $this->Form->input('birth_dt', array(
    'label' => array(
         'text' => 'Date of birth'
     ),
 ));
```

This is a little fix so we can set the label again using the 'quick style' without specifying the text key

### CODE REVIEW

**Comment by slywalker** [comment]
Sorry, test is failed.
I can not merge (T_T)

**Comment by wvdongen** [comment]
The test failed due to CakePHP updates from 2.4.3 to 2.4.4. The test has been fixed.

**Comment by impronta48** [comment]
Very good result!

**Comment by slywalker** [comment]
Thank you :+1:

**Pull request merged**
